/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ItRouteImport } from './routes/it'
import { Route as HrRouteImport } from './routes/hr'
import { Route as EnRouteImport } from './routes/en'
import { Route as DeRouteImport } from './routes/de'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DownloadHeroDotmp4RouteImport } from './routes/download.hero[.]mp4'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ItRoute = ItRouteImport.update({
  id: '/it',
  path: '/it',
  getParentRoute: () => rootRouteImport,
} as any)
const HrRoute = HrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const DeRoute = DeRouteImport.update({
  id: '/de',
  path: '/de',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadHeroDotmp4Route = DownloadHeroDotmp4RouteImport.update({
  id: '/download/hero.mp4',
  path: '/download/hero.mp4',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/de': typeof DeRoute
  '/en': typeof EnRoute
  '/hr': typeof HrRoute
  '/it': typeof ItRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/download/hero.mp4': typeof DownloadHeroDotmp4Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/de': typeof DeRoute
  '/en': typeof EnRoute
  '/hr': typeof HrRoute
  '/it': typeof ItRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/download/hero.mp4': typeof DownloadHeroDotmp4Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/de': typeof DeRoute
  '/en': typeof EnRoute
  '/hr': typeof HrRoute
  '/it': typeof ItRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/download/hero.mp4': typeof DownloadHeroDotmp4Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/de'
    | '/en'
    | '/hr'
    | '/it'
    | '/sitemap.xml'
    | '/download/hero.mp4'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/de'
    | '/en'
    | '/hr'
    | '/it'
    | '/sitemap.xml'
    | '/download/hero.mp4'
  id:
    | '__root__'
    | '/'
    | '/de'
    | '/en'
    | '/hr'
    | '/it'
    | '/sitemap.xml'
    | '/download/hero.mp4'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeRoute: typeof DeRoute
  EnRoute: typeof EnRoute
  HrRoute: typeof HrRoute
  ItRoute: typeof ItRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DownloadHeroDotmp4Route: typeof DownloadHeroDotmp4Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it': {
      id: '/it'
      path: '/it'
      fullPath: '/it'
      preLoaderRoute: typeof ItRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr': {
      id: '/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof HrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de': {
      id: '/de'
      path: '/de'
      fullPath: '/de'
      preLoaderRoute: typeof DeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download/hero.mp4': {
      id: '/download/hero.mp4'
      path: '/download/hero.mp4'
      fullPath: '/download/hero.mp4'
      preLoaderRoute: typeof DownloadHeroDotmp4RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeRoute: DeRoute,
  EnRoute: EnRoute,
  HrRoute: HrRoute,
  ItRoute: ItRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DownloadHeroDotmp4Route: DownloadHeroDotmp4Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
